<?php

namespace Sztukmistrz\Pagina\Entities\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * View
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class View extends EntityRepository
{
}